[package]
name = "bridge-new-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.bridge-new]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.4"
